#!/bin/bash

function install_bashrc() {
  BASHRC=${HOME}/.bashrc
  grep "### Megashell" ${BASHRC} -q > /dev/null || cat >> ${BASHRC} << END
### Megashell
MEGASHELL_PATH=$(pwd)
MEGASHELL_HOSTNAME="${MEGASHELL_HOSTNAME-\h:}"
source \${MEGASHELL_PATH}/bashrc
END
}

function install_vimrc() {
  VIMDIR=${HOME}/.vim
  VIMRC=${HOME}/.vimrc
  # check we can safely use our vimrc
  if [ ! -f ${VIMRC} ] || head -n 1 ${VIMRC} | grep -q '^"Megashell$'
  then
    echo linking vim stuff
    ln -sf $(pwd)/vim/colors ${VIMDIR}/colors
    ln -sf $(pwd)/vim/vimrc ${VIMRC}
  else
    echo "Cannot install vimrc because it seems you're using your own"
  fi
}

while [ $# -gt 0 ]
do
case $1 in
  --no-hostname) MEGASHELL_HOSTNAME="" ;;
esac
shift
done

install_bashrc
install_vimrc
