#!/bin/bash

function install_bashrc() {
#   BASHRC=${HOME}/.bashrc
#   grep "### Megashell" ${BASHRC} -q > /dev/null || cat >> ${BASHRC} << END
# ### Megashell
# MEGASHELL_PATH=$(pwd)
# MEGASHELL_HOSTNAME="${MEGASHELL_HOSTNAME-\h:}"
# source \${MEGASHELL_PATH}/bashrc
# END
  local here=$(dirname $(realpath $0))
  local magic="source $here/bashrc"
  if egrep "^$magic$" -q ${HOME}/.bashrc > /dev/null
  then
    echo "megashell already installed"
    exit 1
  fi
  echo "$magic" >> ${HOME}/.bashrc
}

function __ln() {
  if [ -h $2 ]
  then
    true
  elif [ ! -a $2 ]
  then
    ln -s $1 $2
  else
    echo "Cannot override $2, which is not a link"
    exit 1
  fi
}

function install_vimrc() {
  VIMDIR=${HOME}/.vim
  VIMRC=${HOME}/.vimrc
  # check we can safely use our vimrc
  if [ ! -f ${VIMRC} ] || head -n 1 ${VIMRC} | grep -q '^"Megashell$'
  then
    mkdir -p ${VIMDIR}
    __ln $(pwd)/vim/colors ${VIMDIR}/colors
    __ln $(pwd)/vim/vimrc ${VIMRC}
  else
    echo "Cannot install vimrc because it seems you're using your own"
  fi
}

# while [ $# -gt 0 ]
# do
# case $1 in
#   --no-hostname) MEGASHELL_HOSTNAME="" ;;
# esac
# shift
# done

install_bashrc
install_vimrc
__ln $(pwd)/tmux.conf ${HOME}/.tmux.conf
