"Megashell
syntax on

:colorscheme megashell
set colorcolumn=80
set modeline
set modelines=5
set background=dark
set relativenumber
set autoindent

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
