"Megashell
au BufReadPost buildlog set syntax=buildlog
syntax on

:colorscheme megashell
set colorcolumn=80
set cursorline
set modeline
set modelines=5
set background=dark
set relativenumber
set autoindent
set incsearch
set shiftround

setlocal expandtab
setlocal shiftwidth=4
setlocal softtabstop=4
