#!/bin/bash

function _supergit_complete() {
  local cur="${COMP_WORDS[COMP_CWORD]}"
  suggestions="$(supergit repos)"
  first="${COMP_WORDS[1]}"
  second="${COMP_WORDS[2]}"
  if [ -z "${first}" ] || [ -z "${second}" ]
  then
    case ${first} in
    branch|repos|status)
        ;;
    *)
        suggestions="${suggestions} branch repos status"
        ;;
    esac
  fi
  COMPREPLY=($(compgen -W "${suggestions}" -- ${cur}))
}

complete -F _supergit_complete supergit
